# Generated by Django 3.1.7 on 2021-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Subscription Title')),
                ('amount_per_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount per month')),
                ('access_to_gym_admin', models.BooleanField(default=False, verbose_name='Access To Gym Admin')),
                ('access_to_wall_pics', models.BooleanField(default=False, verbose_name='Access To Wall Pics')),
                ('uploaded_wall_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Wall Num Upload Limit')),
                ('access_feedback_per_month', models.CharField(blank=True, max_length=3, null=True, verbose_name='Feedback Access')),
                ('active_admins', models.CharField(blank=True, max_length=3, null=True, verbose_name='Active Admins')),
                ('clicks_of_advertising_space', models.CharField(blank=True, max_length=5, null=True, verbose_name='Clicks On Advertising Space')),
                ('gym_ads_on_app', models.BooleanField(default=False, verbose_name='Gym Ads')),
                ('announcements', models.BooleanField(default=False, verbose_name='Announcements')),
                ('access_to_biometric_data', models.BooleanField(default=False, verbose_name='Biometric Data Access')),
                ('access_to_sign_up_info', models.BooleanField(default=False, verbose_name='SignUp Info Access')),
            ],
            options={
                'verbose_name': 'SubscriptionPlan',
                'verbose_name_plural': 'SubscriptionPlans',
            },
        ),
    ]
