# Generated by Django 3.1.7 on 2021-07-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='announcements',
            new_name='announcements_create',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='access_to_gym_admin',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='active_admins',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='access_to_gym_staff',
            field=models.BooleanField(default=False, verbose_name='Access To Gym Staff'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='active_gymstaff_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Active Gym Staff Number'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='access_to_biometric_data',
            field=models.BooleanField(default=False, verbose_name='Biometric Data Access of Climbers'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='access_to_sign_up_info',
            field=models.BooleanField(default=False, verbose_name='SignUp Info Access of Climbers'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='amount_per_month',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount per month'),
        ),
    ]
