# Generated by Django 3.1.7 on 2021-07-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210707_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='amount_per_month',
            new_name='amount',
        ),
    ]
