# Generated by Django 3.1.7 on 2021-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210707_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
