# Generated by Django 3.1.7 on 2021-05-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20210512_0619'),
        ('accounts', '0002_userdetails_home_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='list_gym',
            field=models.ManyToManyField(related_name='user_list_gym', to='gyms.GymDetails'),
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='home_gym',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='home_gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_home_gym', to='gyms.gymdetails'),
        ),
    ]
