# Generated by Django 3.1.7 on 2021-05-13 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20210512_0619'),
        ('accounts', '0003_auto_20210512_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='List Name')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='List Name')),
                ('is_common', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_list_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ListCategory',
                'verbose_name_plural': 'ListCategories',
            },
        ),
        migrations.CreateModel(
            name='UserRouteFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('route_progress', models.IntegerField(choices=[(0, 'Projecting'), (1, 'Red Point'), (2, 'Flash'), (3, 'On Sight')], null=True, verbose_name='Route Progress')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='No. of Attempts')),
                ('route_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Route Notes')),
                ('climb_count', models.IntegerField(default=0, verbose_name='Climb Count')),
                ('grade', models.IntegerField(choices=[(0, 'Negative'), (1, 'Normal'), (2, 'Positive')], null=True, verbose_name='Route Progress')),
                ('rating', models.IntegerField(default=0, verbose_name='Route Rating')),
                ('feedback', models.CharField(blank=True, max_length=500, null=True, verbose_name='Route Feedback')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_route_feedback', to='gyms.wallroute')),
            ],
            options={
                'verbose_name': 'UserRouteFeedback',
                'verbose_name_plural': 'UserRouteFeedbacks',
            },
        ),
        migrations.CreateModel(
            name='RouteSaveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_category_route', to='accounts.listcategory')),
                ('route', models.ManyToManyField(related_name='route_save_list', to='gyms.WallRoute')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_route_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RouteSaveList',
                'verbose_name_plural': 'RouteSaveLists',
            },
        ),
    ]
