# Generated by Django 3.1.7 on 2021-05-15 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20210512_0619'),
        ('accounts', '0005_auto_20210514_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroutefeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_route_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routesavelist',
            name='list_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_category_route', to='accounts.listcategory'),
        ),
        migrations.AlterField(
            model_name='userroutefeedback',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_feedback', to='gyms.wallroute'),
        ),
    ]
