# Generated by Django 3.1.7 on 2021-05-18 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210515_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='bouldering',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bouldering'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='grading',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lead_climbing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lead Climbing'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='top_rope',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Top Rope'),
        ),
    ]
