# Generated by Django 3.1.7 on 2021-05-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_auto_20210519_1024'),
        ('accounts', '0007_auto_20210518_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_going', models.IntegerField(choices=[(0, 'Not Selected'), (1, 'Yes'), (2, 'No'), (3, 'May Be')], default=0, verbose_name='Is Going')),
                ('save_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='save_event', to='gyms.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_saved_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SavedEvent',
                'verbose_name_plural': 'SavedEvents',
            },
        ),
    ]
