# Generated by Django 3.1.7 on 2021-05-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_auto_20210519_1024'),
        ('accounts', '0009_savedevent_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedevent',
            name='save_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_event', to='gyms.event'),
        ),
    ]
