# Generated by Django 3.1.7 on 2021-05-27 07:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_wallvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallvisit',
            options={'verbose_name': 'WallVisit', 'verbose_name_plural': 'WallVisits'},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='strength',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='weakness_hold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None, verbose_name='Weakness Holds'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='weakness_move',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None, verbose_name='Weakness Moves'),
        ),
        migrations.AlterIndexTogether(
            name='wallvisit',
            index_together=set(),
        ),
    ]
