# Generated by Django 3.1.7 on 2021-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210527_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='grading',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='bouldering_grading',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bouldering Grading'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='rope_grading',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Rope Grading'),
        ),
    ]
