# Generated by Django 3.1.7 on 2021-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210527_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('priority', models.IntegerField(default=0, verbose_name='Question Priority')),
            ],
            options={
                'verbose_name': 'QuestionAnswer',
                'verbose_name_plural': 'QuestionAnswers',
            },
        ),
    ]
