# Generated by Django 3.1.7 on 2021-06-22 08:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userroutefeedback_gym'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listcategory',
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
        migrations.AddField(
            model_name='listcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='listcategory',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Is Common'),
        ),
    ]
