# Generated by Django 3.1.7 on 2021-06-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210622_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcategory',
            name='is_common',
        ),
    ]
