# Generated by Django 3.1.7 on 2021-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_listcategory_is_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='list_gym',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='home_gym_added_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Home Gym Addition Date'),
        ),
    ]
