# Generated by Django 3.1.7 on 2021-07-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210630_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallvisit',
            name='user',
        ),
        migrations.AddField(
            model_name='wallvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_wall_visit', to=settings.AUTH_USER_MODEL),
        ),
    ]
