# Generated by Django 3.1.7 on 2021-07-07 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_subscriptionplan_interval'),
        ('accounts', '0022_auto_20210706_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan_subscribed',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plan', to='admins.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
