# Generated by Django 3.1.7 on 2021-07-16 11:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210707_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='strength',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='strength_hold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None, verbose_name='Strength Holds'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='strength_move',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None, verbose_name='Strength Moves'),
        ),
    ]
