# Generated by Django 3.1.7 on 2021-08-17 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0026_openfeedback'),
        ('accounts', '0025_auto_20210809_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('route_feedback', models.IntegerField(verbose_name='Route Feedback Id')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='g_gym_visit', to='gyms.gymdetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_gym_visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GymVisit',
                'verbose_name_plural': 'GymVisits',
            },
        ),
    ]
