# Generated by Django 3.1.7 on 2021-05-10 12:13

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gym_name', models.CharField(max_length=100, verbose_name='Gym Name')),
                ('gym_avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gym Image')),
                ('gym_phone_number', models.CharField(max_length=25, verbose_name='Gym Phone Number')),
                ('hours_of_operation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hours Of Operation')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zipcode')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Site coordinate')),
                ('easy_direction_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Easy Directions Link')),
                ('website_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Website Link')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('climbing_level_range', models.IntegerField(blank=True, choices=[(1, 'V1'), (2, 'V2'), (3, 'V3')], null=True, verbose_name='Climbing Level Range')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_admin_approved', models.BooleanField(default=False, verbose_name='Is Admin Approved')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_detail_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GymDetail',
                'verbose_name_plural': 'GymDetails',
            },
        ),
    ]
