# Generated by Django 3.1.7 on 2021-05-10 12:13

import accounts.models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Rope Climbing'), (1, 'Bouldering'), (2, 'Both')], null=True, verbose_name='Climbing Category')),
                ('layout_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gym Layout Image')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gym Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_layout', to='gyms.gymdetails')),
            ],
            options={
                'verbose_name': 'GymLayout',
                'verbose_name_plural': 'GymLayouts',
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='LayoutSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gym Name')),
                ('section_point', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Section Point')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('gym_layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_layout_section', to='gyms.gymlayout')),
            ],
            options={
                'verbose_name': 'LayoutSection',
                'verbose_name_plural': 'LayoutSections',
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='SectionWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wall Image')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wall Name')),
                ('wall_type', models.IntegerField(choices=[(0, 'Strength'), (1, 'Train'), (2, 'Both')], null=True, verbose_name='Wall Type')),
                ('wall_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wall Height')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('gym_layout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_layout_wall', to='gyms.gymlayout')),
                ('layout_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_wall', to='gyms.layoutsection')),
            ],
            options={
                'verbose_name': 'SectionWall',
                'verbose_name_plural': 'SectionWalls',
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='WallRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Route Name')),
                ('grade', models.IntegerField(choices=[(0, 'N V5'), (1, 'V5'), (2, 'P V5'), (3, 'N V6'), (4, 'V6'), (5, 'P V6')], null=True, verbose_name='Route Grade')),
                ('color', models.IntegerField(choices=[(0, 'Orange'), (1, 'Red'), (2, 'Green'), (3, 'Blue'), (4, 'Purple')], null=True, verbose_name='Route Color')),
                ('route_type', models.IntegerField(choices=[(0, 'Endurance'), (1, 'Strength'), (2, 'Training'), (3, 'Competition')], null=True, verbose_name='Route Type')),
                ('setter_tip', models.CharField(blank=True, max_length=200, null=True, verbose_name='Route Setter Tip')),
                ('tag_point', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_route', to=settings.AUTH_USER_MODEL)),
                ('section_wall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_wall_route', to='gyms.sectionwall')),
            ],
            options={
                'verbose_name': 'WallRoute',
                'verbose_name_plural': 'WallRoutes',
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
    ]
