# Generated by Django 3.1.7 on 2021-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_announcement_event_preloadedtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='sub_title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Title'),
        ),
    ]
