# Generated by Django 3.1.7 on 2021-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_auto_20210520_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallroute',
            name='grade',
            field=models.IntegerField(choices=[(0, 'V0'), (1, 'V1'), (2, 'V2'), (3, 'V3'), (4, 'V4'), (5, 'V5'), (6, 'V6'), (7, 'V7'), (8, 'V8'), (9, 'V9'), (10, 'V10'), (11, 'V11'), (12, 'V12'), (13, 'V13'), (14, 'V14'), (15, 'V15')], null=True, verbose_name='Route Grade'),
        ),
    ]
