# Generated by Django 3.1.7 on 2021-05-31 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_auto_20210527_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallroute',
            name='color',
            field=models.IntegerField(choices=[(1, 'Orange'), (2, 'Red'), (3, 'Green'), (4, 'Blue'), (5, 'Purple'), (6, 'Pink'), (7, 'Brown'), (8, 'Gray')], null=True, verbose_name='Route Color'),
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='tag_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
