# Generated by Django 3.1.7 on 2021-05-31 11:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_auto_20210531_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=13, null=True, verbose_name='week days'),
        ),
    ]
