# Generated by Django 3.1.7 on 2021-06-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0009_auto_20210531_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionwall',
            name='category',
            field=models.IntegerField(choices=[(0, 'Rope Climbing'), (1, 'Bouldering'), (2, 'Both')], null=True, verbose_name='Climbing Category'),
        ),
        migrations.AddField(
            model_name='sectionwall',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_wall', to=settings.AUTH_USER_MODEL),
        ),
    ]
