# Generated by Django 3.1.7 on 2021-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_auto_20210601_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymdetails',
            name='hours_of_operation',
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route Name'),
        ),
    ]
