# Generated by Django 3.1.7 on 2021-06-03 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_auto_20210602_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymlayout',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Image Size'),
        ),
        migrations.AddField(
            model_name='sectionwall',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Image Size'),
        ),
    ]
