# Generated by Django 3.1.7 on 2021-06-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_auto_20210603_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymdetails',
            name='climbing_level_range',
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='Bouldering',
            field=models.IntegerField(blank=True, choices=[(1, 'V System'), (2, 'Fontainebleau')], null=True, verbose_name='Bouldering'),
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='RopeClimbing',
            field=models.IntegerField(blank=True, choices=[(1, 'Ydsscale'), (2, 'Francia')], null=True, verbose_name='Rope Climbing'),
        ),
    ]
