# Generated by Django 3.1.7 on 2021-06-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0013_auto_20210604_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='Is Profile Complete'),
        ),
    ]
