# Generated by Django 3.1.7 on 2021-06-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0014_gymdetails_is_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymdetails',
            name='Bouldering',
            field=models.IntegerField(blank=True, choices=[(10, 'V System'), (11, 'Fontainebleau')], null=True, verbose_name='Bouldering'),
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('grading_system', models.IntegerField(choices=[(0, 'Rope Climbing'), (1, 'Bouldering')], verbose_name='Grading System')),
                ('sub_category', models.IntegerField(choices=[(1, 'Ydsscale'), (2, 'Francia'), (10, 'V System'), (11, 'Fontainebleau')], verbose_name='Sub Category')),
                ('sub_category_value', models.CharField(max_length=20, verbose_name='Sub-Category Value')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
                'index_together': {('created_at', 'updated_at')},
            },
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_grade', to='gyms.gradetype'),
        ),
    ]
