# Generated by Django 3.1.7 on 2021-06-16 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0016_auto_20210615_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallroute',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Image Size'),
        ),
    ]
