# Generated by Django 3.1.7 on 2021-06-22 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0017_wallroute_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsection',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Image Size'),
        ),
    ]
