# Generated by Django 3.1.7 on 2021-06-30 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0018_layoutsection_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='blocked_user',
            field=models.ManyToManyField(related_name='blocked_user_by_gym', to=settings.AUTH_USER_MODEL),
        ),
    ]
