# Generated by Django 3.1.7 on 2021-07-01 12:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0019_gymdetails_blocked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
