# Generated by Django 3.1.7 on 2021-07-02 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0020_gymdetails_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymdetails',
            name='document_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Verified'), (3, 'Rejected')], null=True, verbose_name='Document State'),
        ),
        migrations.AddField(
            model_name='gymdetails',
            name='temp_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
