# Generated by Django 3.1.7 on 2021-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0021_auto_20210702_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionwall',
            name='wall_type',
            field=models.IntegerField(choices=[(0, 'Overhang'), (1, 'Slab'), (2, 'Cave')], null=True, verbose_name='Wall Type'),
        ),
    ]
