# Generated by Django 3.1.7 on 2021-07-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0022_auto_20210708_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequestGymDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, verbose_name='Email')),
                ('gym_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gym Name')),
                ('easy_direction_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Easy Directions Link')),
                ('website_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Website Link')),
                ('gym_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_change_request', to='gyms.gymdetails')),
            ],
            options={
                'verbose_name': 'ChangeRequestGymDetail',
                'verbose_name_plural': 'ChangeRequestGymDetails',
            },
        ),
    ]
