# Generated by Django 3.1.7 on 2021-07-26 06:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0023_changerequestgymdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='template_type',
            field=models.IntegerField(default=0, verbose_name='Template Type'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='gyms_announ_search_7456c0_gin'),
        ),
    ]
