# Generated by Django 3.1.7 on 2021-08-02 08:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0024_auto_20210726_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.CharField(max_length=100, verbose_name='Parent')),
                ('child', models.CharField(blank=True, max_length=100, null=True, verbose_name='Child')),
                ('sub_child', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Child')),
                ('sub_child_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Child 1 Level More')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Global Search',
                'verbose_name_plural': 'Global Searchs',
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
    ]
