# Generated by Django 3.1.7 on 2021-08-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0024_auto_20210716_1144'),
        ('gyms', '0025_globalsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('open_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_feedback', to='accounts.userroutefeedback')),
                ('gym_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open Feedback',
                'verbose_name_plural': 'Open Feedbacks',
            },
        ),
    ]
