# Generated by Django 3.1.7 on 2021-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0026_openfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionwall',
            name='reset_timer',
            field=models.DateTimeField(null=True, verbose_name='Reset Timer'),
        ),
    ]
