# Generated by Django 3.1.7 on 2021-08-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0027_sectionwall_reset_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Wall Type Name')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_wall_type', to='gyms.gymdetails')),
            ],
            options={
                'verbose_name': 'WallType',
                'verbose_name_plural': 'WallTypes',
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Wall Type Name')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_route_type', to='gyms.gymdetails')),
            ],
            options={
                'verbose_name': 'WallType',
                'verbose_name_plural': 'WallTypes',
            },
        ),
    ]
