# Generated by Django 3.1.7 on 2021-08-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0028_routetype_walltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionwall',
            name='wall_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.walltype', verbose_name='Wall Type'),
        ),
    ]
