# Generated by Django 3.1.7 on 2021-08-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0029_auto_20210825_0602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routetype',
            options={'verbose_name': 'RouteType', 'verbose_name_plural': 'RouteTypes'},
        ),
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Wall Type Name')),
                ('hex_value', models.CharField(max_length=100, verbose_name='Hex Value')),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_color_type', to='gyms.gymdetails')),
            ],
            options={
                'verbose_name': 'ColorType',
                'verbose_name_plural': 'ColorTypes',
            },
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gyms.colortype', verbose_name='Route Color'),
        ),
    ]
