# Generated by Django 3.1.7 on 2021-08-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0030_auto_20210825_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Route Type Name'),
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_Color', to='gyms.colortype'),
        ),
        migrations.AlterField(
            model_name='wallroute',
            name='route_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_type', to='gyms.routetype'),
        ),
    ]
