# Generated by Django 3.1.7 on 2021-09-14 13:51

import accounts.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0031_auto_20210827_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionwall',
            name='ghost_wall_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghost Wall Image'),
        ),
        migrations.AddField(
            model_name='sectionwall',
            name='ghost_wall_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ghost Wall Name'),
        ),
        migrations.AddField(
            model_name='sectionwall',
            name='ghost_wall_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Ghost Image Size'),
        ),
        migrations.CreateModel(
            name='GhostWallRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('updated_by', models.IntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Route Name')),
                ('image_size', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None, verbose_name='Image Size')),
                ('tag_point', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_route', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_created_by_route', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_route_grade', to='gyms.gradetype')),
                ('section_wall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_wall_route', to='gyms.sectionwall')),
            ],
            options={
                'verbose_name': 'GhostWallRoute',
                'verbose_name_plural': 'GhostWallRoutes',
                'ordering': ['id'],
            },
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', accounts.models.ActiveObjectsManager()),
            ],
        ),
    ]
